/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendaRouteImport } from './routes/venda'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocacaoRouteImport } from './routes/locacao'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImovelIdRouteImport } from './routes/imovel.$id'

const VendaRoute = VendaRouteImport.update({
  id: '/venda',
  path: '/venda',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocacaoRoute = LocacaoRouteImport.update({
  id: '/locacao',
  path: '/locacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImovelIdRoute = ImovelIdRouteImport.update({
  id: '/imovel/$id',
  path: '/imovel/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/administracao': typeof AdministracaoRoute
  '/contato': typeof ContatoRoute
  '/locacao': typeof LocacaoRoute
  '/login': typeof LoginRoute
  '/venda': typeof VendaRoute
  '/imovel/$id': typeof ImovelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/administracao': typeof AdministracaoRoute
  '/contato': typeof ContatoRoute
  '/locacao': typeof LocacaoRoute
  '/login': typeof LoginRoute
  '/venda': typeof VendaRoute
  '/imovel/$id': typeof ImovelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/administracao': typeof AdministracaoRoute
  '/contato': typeof ContatoRoute
  '/locacao': typeof LocacaoRoute
  '/login': typeof LoginRoute
  '/venda': typeof VendaRoute
  '/imovel/$id': typeof ImovelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/administracao'
    | '/contato'
    | '/locacao'
    | '/login'
    | '/venda'
    | '/imovel/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/administracao'
    | '/contato'
    | '/locacao'
    | '/login'
    | '/venda'
    | '/imovel/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/administracao'
    | '/contato'
    | '/locacao'
    | '/login'
    | '/venda'
    | '/imovel/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdministracaoRoute: typeof AdministracaoRoute
  ContatoRoute: typeof ContatoRoute
  LocacaoRoute: typeof LocacaoRoute
  LoginRoute: typeof LoginRoute
  VendaRoute: typeof VendaRoute
  ImovelIdRoute: typeof ImovelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venda': {
      id: '/venda'
      path: '/venda'
      fullPath: '/venda'
      preLoaderRoute: typeof VendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locacao': {
      id: '/locacao'
      path: '/locacao'
      fullPath: '/locacao'
      preLoaderRoute: typeof LocacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imovel/$id': {
      id: '/imovel/$id'
      path: '/imovel/$id'
      fullPath: '/imovel/$id'
      preLoaderRoute: typeof ImovelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdministracaoRoute: AdministracaoRoute,
  ContatoRoute: ContatoRoute,
  LocacaoRoute: LocacaoRoute,
  LoginRoute: LoginRoute,
  VendaRoute: VendaRoute,
  ImovelIdRoute: ImovelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
